---
- name: add PPA repository for PHP 7.1
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: install PHP 7.1 component
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - php7.1-fpm
    - php7.1-cli
    - php7.1-common
    - php7.1-gd
    - php7.1-mysql
    - php7.1-mcrypt
    - php7.1-curl
    - php7.1-intl
    - php7.1-xsl
    - php7.1-mbstring
    - php7.1-zip
    - php7.1-bcmath
    - php7.1-iconv
    - php7.1-imap
    - php7.1-xmlrpc
    - php7.1-dev
    - php7.1-soap
  #when: php_version.stdout.find('PHP 5.6') != -1 or php_version.stdout.find('PHP 7.0') != -1 or php_version.stdout.find('PHP 7.2') != -1
